### ISSUE TITLE
Using GridExcelExporter

### ISSUE THREAD

**Issue by Saje1** [IgniteUI/igniteui-angular2#100]
Hi Guys,

We are writing an Angular 2 Application and need to be able to export the grid to Excel. We have a Jquery extensions file where we can use the jQuery methods of the igrid However when we run the application we get the following error Property 'GridExcelExporter' does not exist on type 'IgniteUIStatic'.

After some looking online it is been told to 

GridExcelExporter is not defined within the imported type definition file (d.ts files). You can add this manually to your typings file to remove the error.

So we added it manually to the igniteui.d.t.s file:

```
interface IgniteUIStatic {
     DataSource: typeof Infragistics.DataSource;

     **GridExcelExporter: any**
}
```

Which we did and it works fine now. However this is not maintainable when we deploy as the d.ts file is a generated file when we run npm install. Is there another solution? Or could this be added?

Many thanks,

Kind regards,

Sajan Patel

**Comment by mpavlinov** [comment]
This is fixed in the latest Ignite UI service release.
