### ISSUE TITLE
Application sample with Angular 2.0

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular2#101]
Take one of the application samples on igniteui.com and recreate it as an Angular application.

http://www.igniteui.com/application-samples

The sample of choice is ER Dashboard.

http://igniteui.com/er-dashboard-sample

**Comment by dkamburov** [comment]
I've created an empty repo - [https://github.com/IgniteUI/ERDashboard-Angular2](https://github.com/IgniteUI/ERDashboard-Angular2)

**Comment by dkamburov** [comment]
Deployed [here](https://igniteui.github.io/ERDashboard-Angular/). This can be closed.
