### ISSUE TITLE
Combo with odata url throws error

### ISSUE THREAD

**Issue by igMPeterson** [IgniteUI/igniteui-angular2#110]
If you set the dataSource it throws:
EXCEPTION: Error in app/igComboTemplate.html:11:5 caused by: Cannot read property 'value' of undefined

If you set the dataSourceUrl it throws:
EXCEPTION: Error in app/igComboTemplate.html:11:5 caused by: Unexpected token u in JSON at position 0

[Uploading igCombo.zip…]()

**Comment by dkamburov** [comment]
The upload is not available.

**Comment by igMPeterson** [comment]
Uploading the sample again as the previous one didn't see to work.

[igCombo.zip](https://github.com/IgniteUI/igniteui-angular2/files/581651/igCombo.zip)
