### ISSUE TITLE
Exception is thrown when assigning array of objects that have get/set in igHierarchicalGrid

### ISSUE THREAD

**Issue by igMPeterson** [IgniteUI/igniteui-angular2#113]
EXCEPTION: Cannot read property 'allChildrenWidgets' of undefined

Is thrown when assigning the data to grid
[igHierarchicalGrid.zip](https://github.com/IgniteUI/igniteui-angular2/files/572523/igHierarchicalGrid.zip)

**Comment by MayaKirova** [comment]
This seems to be already fixed in the latest version. Please get the latest version of the ts files from: https://github.com/IgniteUI/igniteui-angular2/tree/master/src
