### ISSUE TITLE
Webpack error when attempting to add component to .Net Core Angular2 template

### ISSUE THREAD

**Issue by bperry77** [IgniteUI/igniteui-angular2#117]
I am trying to add IgGridComponent to an Angular2 project created from a VS2015 Angular2 template that uses webpack. Details on that template [here](http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/)

I have installed the igniteui-angular2 package (1.1.2) but webpack complains with the following:

> ERROR in ./~igniteui-angular2/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./igniteui in C:\project_path\node_modules\igniteui-angular2 at ./~igniteui-angular2/index.js 21:0-21

New to Angular2 so any help would be appreciated.

Thanks

**Comment by dkamburov** [comment]
In order to resolve this one completely we need to tag a new version of the npm package too
