### ISSUE TITLE
missing igniteui.angular2.js

### ISSUE THREAD

**Issue by jfongp** [IgniteUI/igniteui-angular2#120]
Can igniteui.angular2.js be provided in the src folder? All the files are currently .ts. Thanks.

**Comment by dkamburov** [comment]
It is provided, but it was renamed to index.js so that it can be easily recognized as an npm package:

[https://unpkg.com/igniteui-angular2@1.1.2/index.js](https://unpkg.com/igniteui-angular2@1.1.2)
