### ISSUE TITLE
igniteui.ts gets transpiled even it is excluded in tsconfig as a node module

### ISSUE THREAD

**Issue by jfongp** [IgniteUI/igniteui-angular2#122]
Hi, I am using igniteui-angular2 with visual studio as the IDE. For some reason, unlike other node modules such as angular, zone, or rxjs, this library gets transpiled and put in a node_modules folder in my wwwroot folder. It is the igniteui.ts that gets transpiled. I am new to this and not sure if this has anything to do with the line require('./igniteui') in the index.js file:

var core_1 = require('@angular/core');
var forms_1 = require('@angular/forms');
require('./igniteui');

Not sure if it's because an igniteui.js file is missing. It would really help if the library doesn't get transpiled. Thanks.

**Comment by dkamburov** [comment]
My [last pull request](https://github.com/IgniteUI/igniteui-angular2/pull/121) was about distributing igniteui.js with the npm package. Does it resolve your issue?

**Comment by kdinev** [comment]
I am creating a new tag to update the npm package.

**Comment by jfongp** [comment]
@dkamburov , thanks for your quick response. I got the latest igniteui js and map files from npm but the issue still exists. I have not been able to figure out why igniteui still gets transpiled into my wwwroot/app folder...

In my angular component, I have the following imports:
import { Component } from '@angular/core';
import { IgDoughnutChartComponent } from 'igniteui-angular2';

tsconfig.js:
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "noEmitOnError": true,
    "outDir": "../wwwroot/app"
  },
  "compileOnSave": true,
  "exclude": [
    "../node_modules/igniteui-angular2"
  ]
}

systemjs.config.js
    var map = {
        'app': 'app', 
        '@angular/core': 'lib/@angular/core/index.js',
        'igniteui-angular2': 'lib/igniteui-angular2/index.js'
    };

**Comment by dkamburov** [comment]
The reason is probably that igniteui-angular2.ts copied to lib folder.

Have you tried excluding "node_modules" and "lib/igniteui-angular2"?

**Comment by jfongp** [comment]
@dkamburov , I just tried that. Still having the same issue...

**Comment by dkamburov** [comment]
@jfongp Can you attach a sample to demonstrate this?

**Comment by dkamburov** [comment]
@jfongp Are you still reproducing this one? And can you attach you sample so we can investigate it?

**Comment by mpavlinov** [comment]
@jfongp We haven't heard from you for a while. Were you able to resolve the issue?

**Comment by jfongp** [comment]
@dkamburov @mpavlinov , sorry I have been off work. I still have the same issue but have spent too much time on this. Maybe there's something different about my config. I would close this issue.
