### ISSUE TITLE
IgTree not working with ignite UI OSS version

### ISSUE THREAD

**Issue by jfongp** [IgniteUI/igniteui-angular2#124]
Hi. I was able to use IgTree with the latest CDN version for the core and lob js files:
	<script src="http://cdn-na.infragistics.com/igniteui/latest/js/infragistics.core.js"></script>
	<script src="http://cdn-na.infragistics.com/igniteui/latest/js/infragistics.lob.js"></script>

However, when I used the OSS Ignite UI version instead which comes with infragistics.core-lite.js and infragistics.core-lob.js, I got the following error:

EXCEPTION: Uncaught (in promise): Error: Error in app/Components/product.component.html:26:21 caused by: $.ig.HierarchicalDataSource is not a constructor
TypeError: $.ig.HierarchicalDataSource is not a constructor
    at $.(anonymous function).(anonymous function)._initDataSource (lib/ignite-ui/js/infragistics.lob-lite.js:164:11573)

According to the product matrix on IgniteUI's github, the tree component is supported by the OSS version as well.

Thank you.

**Comment by dkamburov** [comment]
This is not related to igniteui-angular2. I am able to reproduce it without angular. Here's a [fiddle](http://jsfiddle.net/dkamburov/6bcn9vvr/1/) without Angular.
It seems that infragistics.datasource.js file is not included into the infragistics.core-lite.js.
To work it around you could add a reference to the infragistics.datasource.js
Here's a [working fiddle](http://jsfiddle.net/dkamburov/6bcn9vvr/2/)

These are the used references:
```
<script src="https://npm-cdn.herokuapp.com/ignite-ui@16.2.2040/js/infragistics.core-lite.js"></script>
<script src="https://npm-cdn.herokuapp.com/ignite-ui@16.2.2040/js/modules/infragistics.datasource.js"></script>
<script src="https://npm-cdn.herokuapp.com/ignite-ui@16.2.2040/js/infragistics.lob-lite.js"></script>
```

**Comment by dkamburov** [comment]
I'm closing the issue, it should be resolved now.
