### ISSUE TITLE
Error is thrown when there is initially fixed column

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular2#134]
Attached is a sample that demonstrates the issue.
[ng2ColumnFixing.zip](https://github.com/IgniteUI/igniteui-angular2/files/799249/ng2ColumnFixing.zip)

**Comment by dkamburov** [comment]
related to #167

**Comment by dkamburov** [comment]
I tested it and it seems resolved. Also attaching modified sample.
[ng2columnTemplate_modified.zip](https://github.com/IgniteUI/igniteui-angular2/files/1306839/ng2columnTemplate_modified.zip)
