### ISSUE TITLE
PivotGrid crashes when expanding on Row-wise - TypeError: a.substr is not a function

### ISSUE THREAD

**Issue by snkrishnan1** [IgniteUI/igniteui-angular2#142]
I am trying to load a PivotGrid and when I try to expand on Row-wise the pivot-grid crashes and stops working. Please find attached the code, sample json data to replicate the scenario. also find the snapshot attached which explains the scenario. I am getting the exception "TypeError: a.substr is not a function"

Any ideas why I am getting this exception?
[a.substr Issue.zip](https://github.com/IgniteUI/igniteui-angular2/files/848220/a.substr.Issue.zip)

**Comment by snkrishnan1** [comment]
StackTrace for this issue:
"TypeError: a.substr is not a function
    at Class.aj (http://localhost:49928/js/IgniteUI/infragistics.lob.js:587:2109)
    at Class.al (http://localhost:49928/js/IgniteUI/infragistics.lob.js:587:1316)
    at Class.al (http://localhost:49928/js/IgniteUI/infragistics.lob.js:587:2023)
    at Class.t (http://localhost:49928/js/IgniteUI/infragistics.lob.js:586:23395)
    at Class.discoverMembersAsync (http://localhost:49928/js/IgniteUI/infragistics.lob.js:586:21925)
    at Class.getMembersOfLevel (http://localhost:49928/js/IgniteUI/infragistics.lob.js:585:27626)
    at Class.am (http://localhost:49928/js/IgniteUI/infragistics.lob.js:557:14429)
    at Class.update (http://localhost:49928/js/IgniteUI/infragistics.lob.js:557:4234)
    at Class.update (http://localhost:49928/js/IgniteUI/infragistics.lob.js:557:21882)
    at e.(anonymous function).(anonymous function)._updateGrid (http://localhost:49928/js/IgniteUI/infragistics.lob.js:661:26638)"

**Comment by dkamburov** [comment]
Can you send the whole app for further investigations?
I tried, but wasn't able to reproduce it. It could be something from your pivot grid configuration and more specifically the aggregators.

I had to change  this `(IIF(LYUnitsSold2Week != 0,((UnitsSold2Week - LYUnitsSold2Week) / LYUnitsSold2Week),0))` to `(LYUnitsSold2Week != 0 ? ((UnitsSold2Week - LYUnitsSold2Week) / LYUnitsSold2Week) : 0)` so I could be able run it. I also used smaller amount of data. But at the end had no problem with expansions of the rows.
![screenshot1](https://cloud.githubusercontent.com/assets/1182001/24095280/0b1291c8-0d65-11e7-9a09-db496b3f5d59.png)

**Comment by snkrishnan1** [comment]
I am attaching all the relevant code related to this issue. I tried with relatively lesser amount of data and the issue is still reproducible. It didn't have this logic in it, still the issue exists.
(IIF(LYUnitsSold2Week != 0,((UnitsSold2Week - LYUnitsSold2Week) / LYUnitsSold2Week),0)) to (LYUnitsSold2Week != 0 ? ((UnitsSold2Week - LYUnitsSold2Week) / LYUnitsSold2Week) : 0)

Please revert back if you need more info

Please find the stack trace
Error occurred. TypeError: a.substr is not a function
:49928/app/Common/CustomErrorHandler.js:20 Stack Trace : TypeError: a.substr is not a function
    at Class.aj (http://localhost:49928/js/IgniteUI/infragistics.lob.js:587:2109)
    at Class.al (http://localhost:49928/js/IgniteUI/infragistics.lob.js:587:1316)
    at Class.al (http://localhost:49928/js/IgniteUI/infragistics.lob.js:587:2023)
    at Class.t (http://localhost:49928/js/IgniteUI/infragistics.lob.js:586:23395)
    at Class.discoverMembersAsync (http://localhost:49928/js/IgniteUI/infragistics.lob.js:586:21925)
    at Class.getMembersOfLevel (http://localhost:49928/js/IgniteUI/infragistics.lob.js:585:27626)
    at Class.am (http://localhost:49928/js/IgniteUI/infragistics.lob.js:557:14429)
    at Class.update (http://localhost:49928/js/IgniteUI/infragistics.lob.js:557:4234)
    at Class.update (http://localhost:49928/js/IgniteUI/infragistics.lob.js:557:21882)
    at e.(anonymous function).(anonymous function)._updateGrid (http://localhost:49928/js/IgniteUI/infragistics.lob.js:661:26638)

[cacheurl-Json Data-cacheDataService.GetData.txt](https://github.com/IgniteUI/igniteui-angular2/files/855219/cacheurl-Json.Data-cacheDataService.GetData.txt)
[configService.GetWidgetConfig - Json data.txt](https://github.com/IgniteUI/igniteui-angular2/files/855218/configService.GetWidgetConfig.-.Json.data.txt)
![pivotgrid a substr not a function error](https://cloud.githubusercontent.com/assets/19292236/24103732/8d04de34-0d56-11e7-8327-d778d2e13b76.png)
[PivotGrid.ts.txt](https://github.com/IgniteUI/igniteui-angular2/files/855241/PivotGrid.ts.txt)
[SlideOut.ts.txt](https://github.com/IgniteUI/igniteui-angular2/files/855240/SlideOut.ts.txt)
[PivotGrid.html.txt](https://github.com/IgniteUI/igniteui-angular2/files/855247/PivotGrid.html.txt)
[SlideOut.html.txt](https://github.com/IgniteUI/igniteui-angular2/files/855246/SlideOut.html.txt)

**Comment by dkamburov** [comment]
I've tested it with the most recent files and expansion of the rows is working as expected.
Please review, update and send back the runnable sample, I'm attaching, so I could reproduce this on my side.

To run it: 
```
npm install
npm start
```
[sample.zip](https://github.com/IgniteUI/igniteui-angular2/files/857755/sample.zip)

**Comment by snkrishnan1** [comment]
We tried with the sample which has hard coded data of JSON values and it works fine sent by you. But we are still facing issues with this. Can you please try by reading the JSON values directly from this link and let us know if it works for you? I am providing with different set of JSON values and want to know how it works for you?

this.result = [] should be populated with JSON values directly read from the link http://www.mindtreedevmind.com/FireboltRedisApi/api/Query/Corporate/12721 

var widgetConfigData = '{"columns":"","measures":"[Measures].[Sold_Dollars],[Measures].[Sold_Units]","rows":"[Item_Id].[Item_Id]","metadata":{"cube":{"dimensions":[{"hierarchies":[{"levels":[{"memberProvider":"function (item) { return \"Total Rtlr Name\"; }","caption":"Total Rtlr Name","name":"TotalRtlr_Name"},{"memberProvider":"function (item) { return item.Rtlr_Name; }","caption":"Rtlr Name","name":"Rtlr_Name"}],"caption":"Rtlr Name","name":"Rtlr_Name"}],"caption":"Rtlr Name","name":"Rtlr_Name"},{"hierarchies":[{"levels":[{"memberProvider":"function (item) { return \"Total Item Id\"; }","caption":"Total Item Id","name":"TotalItem_Id"},{"memberProvider":"function (item) { return item.Item_Id; }","caption":"Item Id","name":"Item_Id"}],"caption":"Item Id","name":"Item_Id"}],"caption":"Item Id","name":"Item_Id"},{"hierarchies":[{"levels":[{"memberProvider":"function (item) { return \"Total Item Desc\"; }","caption":"Total Item Desc","name":"TotalItem_Desc"},{"memberProvider":"function (item) { return item.Item_Desc; }","caption":"Item Desc","name":"Item_Desc"}],"caption":"Item Desc","name":"Item_Desc"}],"caption":"Item Desc","name":"Item_Desc"}],"measuresDimension":{"measures":[{"aggregator":"function(items, cellMetadata) { var sum = 0; $.each(items, function(index, item) { sum += item.Sold_Dollars; } );   $.ig.regional.defaults.currencyMaxDecimals = 0;   $.ig.regional.defaults.currencyMinDecimals = 0;   return $.ig.formatter(parseFloat(sum), \"number\", \"#########0\"); }","caption":"Sold Dollars","name":"Sold_Dollars"},{"aggregator":"function(items, cellMetadata) { var sum = 0; $.each(items, function(index, item) { sum += item.Sold_Units; } );   $.ig.regional.defaults.currencyMaxDecimals = 0;   $.ig.regional.defaults.currencyMinDecimals = 0;   return $.ig.formatter(parseFloat(sum), \"number\", \"#########0\"); }","caption":"Sold Units","name":"Sold_Units"},{"aggregator":"function(items, cellMetadata) { var sum = 0; $.each(items, function(index, item) { sum += item.Rtlr_Price; } );   $.ig.regional.defaults.currencyMaxDecimals = 0;   $.ig.regional.defaults.currencyMinDecimals = 0;   return $.ig.formatter(parseFloat(sum), \"number\", \"#########0\"); }","caption":"Rtlr Price","name":"Rtlr_Price"},{"aggregator":"function(items, cellMetadata) { var sum = 0; $.each(items, function(index, item) { sum += item.Rtlr_Cost; } );   $.ig.regional.defaults.currencyMaxDecimals = 0;   $.ig.regional.defaults.currencyMinDecimals = 0;   return $.ig.formatter(parseFloat(sum), \"number\", \"#########0\"); }","caption":"Rtlr Cost","name":"Rtlr_Cost"}],"name":"Measures"},"caption":"Report substr Sample Recreated Diff World","name":"Report substr Sample Recreated Diff World"}}}'	
	
Please let us know with this data if it works for you and your analysis?
Thanks

**Comment by snkrishnan1** [comment]
Any updates on this?

**Comment by dkamburov** [comment]
I used 48" and 8" into the values and the new pivot grid configuration and data and still cannot reproduce what you're facing.
I'm attaching the new sample, please modify it and send it back for investigations.
[sample2.zip](https://github.com/IgniteUI/igniteui-angular2/files/874869/sample2.zip)

**Comment by snkrishnan1** [comment]
![item_id converted to number sorting doesnot happen](https://cloud.githubusercontent.com/assets/19292236/24473487/78bc98c0-1497-11e7-83df-22de3f26488d.png)
![item_id converted to number substr is not function issue](https://cloud.githubusercontent.com/assets/19292236/24473488/78bd1412-1497-11e7-914d-c27ca69cdd29.png)

As per our analysis, we found that if we have the dimensions columns (Row Headers) as number datatype, then this issue occurs. Please refer the snapshot attached. the column Item_Id comes as string which is read from JSON through a API service. In our application we have written some custom code to convert all the numeric columns to number datatype so that we do some manipulations dynamically (in the client browser) on those columns like exception highlighting based on numeric values, KPI indicators, IIF condition operators etc. Similarly the column Item_Id is also a numeric and hence it is converted to a number datatype. since it is a number datatype, we are not able to expand on that dimensions and getting this error earlier. But if we avoid changing this dimensions to a number datatype then it works fine.
Issues we are facing now and help required from your team is as below:- 
1. we need to convert the dimensions to number datatype if it belongs to numeric, because sorting doesn't happen if the dimensions is in string datatype. Please refer snapshot attached

Can you please help us how to resolve this issue?

Please find the attached code along with sample json data

**Comment by dkamburov** [comment]
First add `levelSortDirections `to `optsGrid` 
```
levelSortDirections: [
    { levelUniqueName: "[Item_Id].[Item_Id].[Item_Id]", sortDirection: "descending" }
],
```
and it is resolving the `a.substr` issue. You are having string values for `Item_Id` and they are being sorted as you expected initially (as numbers).

Second in order to sort the `Sold Dollars` as numbers you have to pass them as numbers to the dataSource.
So change this `$.ig.formatter(parseFloat(sum), \\"number\\", \\"#########0\\");` to `parseFloat(sum)` and sorting gets fixed, but now we don't have the formatting you used to have.

Actually the igPivotGrid is based on igGrid, so you can bind to `rendering` event and apply formatting to the columns of the igGrid:
```
gridOptions: {
    rendering: function(e, ui) {
       for (var i = 0; i < ui.owner.options.columns.length; i++) {
           ui.owner.options.columns[i].formatter = function (val, rec) {
               return jQuery.ig.formatter(val, "number", "#########0");
           }
       };
    }
}
```

And here's the modified sample for a reference.
[Sample.zip](https://github.com/IgniteUI/igniteui-angular2/files/885884/Sample.zip)

**Comment by snkrishnan1** [comment]
This solution works for me, thanks
