### ISSUE TITLE
Getting error IgniteUI-Angular2 with ASP.Net Core 1.1 on VS 2017 Error: jQuery is not defined

### ISSUE THREAD

**Issue by rishisharma1510** [IgniteUI/igniteui-angular2#145]
I am working on project created from angular2 ASP.Net core 1.1 SPA Template using Visual Studio 2017.
To create the project, here are the steps:
open command promp
1. move to the directory where u want to create the project
2. dotnet new -l
	list all the templates
3. dotnet new angular
4.dir to check the directories that got created
5. dotnet restore
6. npm install

And opened it in Visual Studio 2017 Community

. Then started adding components and tried to use IgniteUI-Angular2 IgGrid.
But I am getting error as jquery is not defined.

Could you please provide me the sample for using editable IG-Grid build in Visual studio 2017, Angular2 with ASP.Net Core 1.1 SPA Template like I created it using above mentioned steps
My code is available at https://github.com/rishisharma1510/TestInginiteUI-Angular2

Could anybody please help me in this

**Comment by rishisharma1510** [comment]
Could anybody please help me with this?

**Comment by kdinev** [comment]
@rishisharma1510 I didn't have a chance to run your sample yet, but it sounds to me like you forgot to reference the jQuery script?

**Comment by rishisharma1510** [comment]
I added the references but its keep on giving same error.
It would be very helpful if you can download my code and try to help me fixing this issue.

**Comment by kdinev** [comment]
@rishisharma1510 I see you're using webpack. I think that's where the issue is coming from. I'm not sure if we currently integrate well with webpack, so I'll defer this back to @dkamburov

**Comment by dkamburov** [comment]
Disable server side pre-rendering. More info on this here - http://www.infragistics.com/community/forums/t/108580.aspx

Also you need to add jquery, jqueryui and the references to Ignite UI. I've simply included them to the layout. 
Also note the 'ig-options' is actually 'options', the id of the grid should be defined. I'm attaching the modified project.
[AIR.Cyber.Web.Presentation_IgniteUIAngular2_Core_VS2017.zip](https://github.com/IgniteUI/igniteui-angular2/files/875373/AIR.Cyber.Web.Presentation_IgniteUIAngular2_Core_VS2017.zip)

**Comment by rishisharma1510** [comment]
Thanks a lot for the.. I appreciate it a lot.

I just have a quick question. I am using service in the same sample. and on button click I need to populate the data. And its not populating the grid inspite of the fact that data is populated from same collection in a html table but not in ignite ui. I am suspecting is it due to server side prerendering that we have disabled. Could you please guide me on this as well

**Comment by dkamburov** [comment]
You'll need to use the dataSource attribute and assign the data to the property which was referenced there.

`<ig-grid [(options)]="gridOptions" [(dataSource)]="contracts"  [(widgetId)]='id'></ig-grid>`

and then the service should modify contracts `this.contracts = this.exposureService.getexposures();`

Attaching the modified sample
[AIR.Cyber.Web.Presentation_IgniteUIAngular2_Core_VS2017.zip](https://github.com/IgniteUI/igniteui-angular2/files/885077/AIR.Cyber.Web.Presentation_IgniteUIAngular2_Core_VS2017.zip)

**Comment by rishisharma1510** [comment]
Thank you so much for the sample.. It worked perfectly... 
I am trying to add a column of dropdown type... The dropdown has to be populated with the data coming from service.  I found lot of articles on internet but none of them are working

Here is my Typescript file for ContractList

import { Inject, Component } from '@angular/core';
import { ExposureService } from '../../services/exposure.service';
import { ContractModel } from '../../models/contract.model';
import { CategoryModel } from '../../models/category.model';
import { EmitterService } from '../../services/emitter.service';
import { Http } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import { ConfigurationModel } from '../../models/configuration.model';
import { ReferenceService } from '../../services/reference.service';
declare var jQuery: any;

@Component({
    selector: 'contract-list',
    templateUrl: './contractlist.component.html',

})


export class ContractListComponent {

    private gridOptions: IgGrid;
    configurationModel: ConfigurationModel;
    isNewExposure: boolean;
    public contractTypeCodes: CategoryModel[] = [];
    public contracts: ContractModel[] = [];
    public id: string = "grid1";
    errorMessage: string;
    constructor(private referenceService: ReferenceService, private exposureService: ExposureService, private emitterService: EmitterService) {
        this.GetCategoryCode();
        this.gridOptions = {
            //dataSource: this.contracts,
            width: "100%",
            primaryKey: "contractSID",
            responseDataKey: "results",
            autoCommit: true,
            autoGenerateColumns: false,
            columns: [
                { "headerText": "contractSID", "key": "contractSID", "dataType": "number", "width": "10%", hidden: true },
                { "headerText": "contractID", "key": "contractID", "dataType": "string", "width": "10%" },
                {
                    "headerText": "contractTypeCode", "key": "contractTypeCode", "dataType": "string", "width": "10%", formatter: this.formatCategoryCombo
                },
                { "headerText": "perilSetCode", "key": "perilSetCode", "dataType": "string", "width": "10%" },
                { "headerText": "currencyCode", "key": "currencyCode", "dataType": "string", "width": "10%" },
                { "headerText": "inceptionDate", "key": "inceptionDate", "dataType": "date", "width": "10%" },
                { "headerText": "expirationDate", "key": "expirationDate", "dataType": "date", "width": "10%" },
                { "headerText": "userLineOfBusiness", "key": "userLineOfBusiness", "dataType": "string", "width": "10%" },
                { "headerText": "insuredName", "key": "insuredName", "dataType": "string", "width": "10%" },
                { "headerText": "submitStatusCode", "key": "submitStatusCode", "dataType": "string", "width": "10%" },
                { "headerText": "userDefined1", "key": "userDefined1", "dataType": "string", "width": "10%" },


            ],
            features: [
                {
                    name: "Updating",
                    //columnSettings: [{
                    //    //The combo is defined as an editor provider. Combo options are defined under 'editorOptions'.
                    //    columnKey: "contractTypeCode",
                    //    editorType: 'Combo',
                    //    required: true,
                    //    editorOptions: {
                    //        mode: "DropDown",
                    //        dataSource: this.categoryCodes,
                    //        textKey: "categoryName",
                    //        valueKey: "categoryCode"
                    //    }
                    //}]
                    columnSettings: [{
                        //The combo is defined as an editor provider. Combo options are defined under 'editorOptions'.
                        columnKey: 'contractTypeCode',
                        editorType: 'combo',
                        required: false,
                        editorOptions: {
                            mode: 'dropdown',
                            dataSource: this.contractTypeCodes,
                            responseDataKey: 'value',
                            textKey: 'categoryName',
                            textKeyType: "string",
                            valueKey: 'categoryCode',
                             valueKeyType: "string",
                        }
                    }]
                },
                {
                    name: "Selection",
                    mode: "single"
                },
                {
                    name: "Filtering"
                },
                {
                    name: "Sorting"
                },
                {
                    name: "Paging",
                    pageSize: 10
                },
            ]
        };

      

        this.emitterService.getConfiguration().subscribe(configurationModel => {
            this.configurationModel = configurationModel;
            this.PopulateContractList();
        });

        this.emitterService.getSaveConfiguration().subscribe(isNewExposure => {
            this.isNewExposure = isNewExposure;
            this.SaveContracts();
        });
    }

    GetCategoryCode() {
        var cat = this.contractTypeCodes;

        this.referenceService.getcategorycode("ContractTypeCode")
            .subscribe(
            contract => this.contractTypeCodes = contract,
            error => this.errorMessage = <any>error);
    }

    SaveContracts() {

        this.configurationModel.ExposureSetName = this.configurationModel.ExposureSetName;
    }

    formatCategoryCombo(val) {
        var i, category;
        if (this.contractTypeCodes != undefined) {
            for (i = 0; i < this.configurationModel.ContractTypeCodes.length; i++) {
                category = this.configurationModel.ContractTypeCodes[i];
                if (category.ID == val) {
                    val = category.Name;
                }
            }
        }
        return val;
    }

 

    PopulateContractList() {
        //this.configurationModel.ContractTypeCodes = this.contractTypeCodes;
        this.exposureService.getcontracts(this.configurationModel.DatabaseName, this.configurationModel.ExposureSetSid)
            .subscribe(
            contract => this.contracts = contract,
            error => this.errorMessage = <any>error);

        //this.gridOptions.dataSource = this.contracts;
    }
}

I debug and found that when the formatter method is called, it founds the collection for the dropdown as undefined. Dowpdown is not getting populated with data even though i set the datasource.

Could you please guide me or provide a sample for it?

**Comment by dkamburov** [comment]
The collection is not defined, because the formatter callback is using different context. When defining it you can apply the formatter callback with the current context `jQuery.proxy(this.formatCategoryCombo, this)`

But afterwards when applying the combo data source you'll have to reapply the `gridOptions `so that the grid can be recreated and can use the new combo dataSource.

Here's a sample to demonstrate this.
[AIR.Cyber.Web.Presentation_IgniteUIAngular2_Core_VS2017 (2).zip](https://github.com/IgniteUI/igniteui-angular2/files/927784/AIR.Cyber.Web.Presentation_IgniteUIAngular2_Core_VS2017.2.zip)

**Comment by rishisharma1510** [comment]
That's Interesting...
But if we have to populate another dropdown based on selection of first dropdown value within the same grid, then recreating gridoption doesn't work. Could you please suggest some solution for that?

**Comment by dkamburov** [comment]
Are you using editMode: "cell"?
Can you please attach your sample for investigations?

**Comment by rishisharma1510** [comment]
Do we have any way to a two way binding for the combo within the grid? If we have option to do the two way binding to the datasource of combo then we don't have to render grid again and data will be reflected in the dropdown without any hastle. Could you please guid me on this?

**Comment by dkamburov** [comment]
The combo is initialized through the grid, not throught the angular IgComboComponent so it is not going to have two way data binding out of the box, you need handle the data updates on yourself.

**Comment by dkamburov** [comment]
Closing this one due to inactivity, if you have further questions please re-open it
