### ISSUE TITLE
Not compatible with latest versions?

### ISSUE THREAD

**Issue by KristofferBerge** [IgniteUI/igniteui-angular2#148]
What version is this compatible with? 

The directive option is no longer a part of the component-decorator. So instead I add the component I try to use as a declaration in my app module via the ng-module decorator. But when I try to use a component I get an error saying that both of the two mandatory attributes `options` and `widgetId` is not a known property of the component.

Is there something I have missed here or is this not compatible with recent versions of angular2?

**Comment by kdinev** [comment]
@KristofferBerge Are you trying this with Angular 4?

**Comment by dkamburov** [comment]
@KristofferBerge I created an app with angular-cli and added IgGridComponent to declarations of the NgModule:
```
  declarations: [
    AppComponent,
    IgGridComponent
  ],
```
And its working, I'm attaching the sample. 
Make sure you haven't misspelled the component or its selector into the template.


[ig-app.zip](https://github.com/IgniteUI/igniteui-angular2/files/889477/ig-app.zip)

**Comment by KristofferBerge** [comment]
My bad here. I didn't import the igniteui in adittion to the jquery libraries. 

I really think the documentation should be updated to reflect the current state of angular2. I didn't find much help in the documentation when I tested this out. It should really specify that the frameworks has to be imported and how. Right now I'm using CDN for both jQuery and igniteui. Is it possible to use npm packages for the dependencies without declaring the libraries as script tags in index.html? Would be nice to get warnings for unmet dependencies when running npm install.

I'm also struggeling to see why I should use this instead of using the jquery-library directly which is already imported anyway. Seems like I'm only importing more code. I'm not saying there aren't any, but I would really like to see a list of benefits of using this to help me decide if this is something I should try out or not.

@kdinev Wow. Really?

**Comment by kdinev** [comment]
@KristofferBerge Yeah, I was asking because we've not officially updated to support Angular 4 yet. We will soon though.

**Comment by KristofferBerge** [comment]
Haha, I thought you where joking. Didn't know there where such a thing.

**Comment by dkamburov** [comment]
@KristofferBerge 
You can load the desired scripts without having them into the index.html file.
Simply download Ignite UI product to igniteui folder and include them into the scripts and styles sections in .angular-cli.json:


 ```
     "styles": [
        "styles.css",
        "../igniteui/css/themes/infragistics/infragistics.theme.css",
        "../igniteui/css/structure/infragistics.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/jquery-ui-dist/jquery-ui.min.js",
        "../igniteui/js/infragistics.core.js",
        "../igniteui/js/infragistics.lob.js"
      ],
```

[ig-app1.zip](https://github.com/IgniteUI/igniteui-angular2/files/890390/ig-app1.zip)

**Comment by KristofferBerge** [comment]
The problem with doing this is that it doesn't build. Unzipped your example and ran npm install and then ng build --prod. The build fails.

**Comment by dkamburov** [comment]
`ng build` is working fine. 
If you are trying the production build `ng build --prod`, I believe that this is an issue with angular cli, because `ng build` is executing with no errors.

**Comment by KristofferBerge** [comment]
Ok, I think i understand now. 
It wouldn't build because you where refering to an empty igniteui folder where I was supposed to put my ignite ui package since the version offered on npm does not include any charts og grids for some reason.

**Comment by dkamburov** [comment]
That's right.
You can see the list of open source widgets [here](https://github.com/IgniteUI/ignite-ui#available-features-in-ignite-ui-open-source-version)
