### ISSUE TITLE
Internal modifications to the columns collection cause diff to re-render grid on initialization

### ISSUE THREAD

**Issue by mharrington622** [IgniteUI/igniteui-angular2#155]
Steps to Reproduce:
1. Run [attached sample](https://github.com/IgniteUI/igniteui-angular2/files/962842/bug_igniteui-angular-cli-test-master.zip) (npm install & npm start, localhost:4200)
2. Click "Load Grid" button

Actual Result:
The alert in the rendered event handler fires twice

Expected Result:
The alert in the rendered event handler fires once

Notes:
In IgGridBase.ngDoCheck > IgControlBase.optionChange > IgControlBase.equalsDiff, differences are being returned due to the readOnly property being added as well as properties in the last column due to autofitLastColumn.

**Comment by dkamburov** [comment]
The same reason causes issue #134

**Comment by dkamburov** [comment]
Tested with "igniteui-angular2": "4.0.4" and the issue is resolved, I believe it was fixed with #167
