### ISSUE TITLE
Need help in formating and sorting the Dates in the column headers in PivotGrid

### ISSUE THREAD

**Issue by snkrishnan1** [IgniteUI/igniteui-angular2#157]
We are facing some issues in formating and sorting the Dates in the column headers in PivotGrid. From our research in the forums of Infragistics we understand we need to have the hierarchy for the dates, i.e. Year/Month/Dates etc. But as per our business requirements we can't have any hierarchy, instead we need it in the format as specified in the snapshot attached. Also please find the code/pivotgrid angular component and the data used for binding the grid.
[DateFormatIssue.zip](https://github.com/IgniteUI/igniteui-angular2/files/1005154/DateFormatIssue.zip)

**Comment by MayaKirova** [comment]
The date does not necessarily have to be a multi-level hierarchy. You can define a simple one level hierarchy with a memberProvider function that can return the data formatted the way you want to display it in the header/rows.
For example:
                            {
                                caption: "Date", name: "Date", hierarchies: [
                                    {
			name: "Dates", caption: "Date", levels: [
			{name: "Date", caption: "Date",   memberProvider: function (item) {  return item.Date;} }
			]
			}
                                ]
                            }

If you’d like to apply some additional formatting to the value you could use the  $.ig.formatter and pass the specific date format you want to use, for example:
memberProvider: function (item) {  return $.ig.formatter( new Date(item.Date), "date", "MM/dd/yyyy hh:mm:ss tt"); } 

Regarding sorting, you can refer to the following sample that demonstrates how to enable and apply initial sorting:
https://www.igniteui.com/pivot-grid/sorting

Let me know if you have any additional qustions.

**Comment by SlavUI** [comment]
Closing the issue @snkrishnan1  if you have any further questions please let us know
