### ISSUE TITLE
columnVirtualization Mode

### ISSUE THREAD

**Issue by ProofWoW** [IgniteUI/igniteui-angular2#162]
Hi, have a problem, cant set columnVirtualization to true. Angular2 igTreeGrid
OPTIONS:
                       _virtualizationMode: "fixed",
                       columnVirtualization: true,
		       dataSource: this.data,
		       rowVirtualization: false,
		       height: "600px"_

Error:
**caused by: Row Virtualization requires a different virtualizationMode setting. The virtualizationMode should be set to 'continuous'.**

But option  "rowVirtualization: false" is false

where is problem?
Thanks

**Comment by kdinev** [comment]
@ProofWoW The only virtualization mode supported by the `igTreeGrid` is `continuous`. However, `columnVirtualization` is supported only in `fixed` mode, thus column virtualization is not supported by the `igTreeGrid`

https://www.igniteui.com/help/igtreegrid-overview#performance
