### ISSUE TITLE
Binding on widgets gets removed when routing away and back to page

### ISSUE THREAD

**Issue by mharrington622** [IgniteUI/igniteui-angular2#165]
Steps to reproduce:

1. Run [attached sample](https://github.com/IgniteUI/igniteui-angular2/files/1074776/lpmUI.zip) (npm install, npm start)
2. Open localhost:4200 and click on "Dummy" in top left corner.
3. Press browser's back button or select "Home".
4. Click on either the grid or the chart in the tiles.

Actual result:
The height of the grid/chart doesn't change.

Expected result:
The height of the grid/chart should expand.

Other Notes:
If you try to expand the grid/chart on initial load before routing away, the height expands as expected.

**Comment by MayaKirova** [comment]
This seems to be an issue in the actual Angular framework.
When a change is initiated by a parent component the child component does not reflect the change after navigation has occurred.
It can be reproduced outside of the our Angular2 components. I’ve attached a sample where none of the components are used. 
Just a button on the parent component with a click handler that initiates call to a method of the child component where a text property is changed.
The change is properly reflected in the child component until you’ve navigated to another page and then came back.

I suggest that you check the Angular2 repo and see if perhaps there is a similar issue already there and if not log it.
https://github.com/angular/angular/issues

[lpmUI_modified.zip](https://github.com/IgniteUI/igniteui-angular2/files/1518849/lpmUI_modified.zip)
