### ISSUE TITLE
The rendered event of the grid is fired twice

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular2#167]
Open [http://igniteui.github.io/igniteui-angular2/](http://igniteui.github.io/igniteui-angular2/) and inspect the console.

You can see that the event is triggered twice. The rendered event should be triggered only once.

**Comment by ankeshdave** [comment]
Any update on this ?

**Comment by mpavlinov** [comment]
Currently we're working on fixing it.

**Comment by ankeshdave** [comment]
Is this fix released as a package? , I would like to use this in my production application.
