### ISSUE TITLE
IgHierarchicalGrid two way data binding not working

### ISSUE THREAD

**Issue by LiquidSean** [IgniteUI/igniteui-angular2#168]
**DOES NOT WORK**
<ig-hierarchical-grid [(widgetId)]='id2' 
[options]="hgridOptions" [(dataSource)]="list" class="table-responsive">
    </ig-hierarchical-grid>
****

Our data source is being retrieved in ngOnInit and in the constructor the grid options are being set. The two way data binding is working for the igGrid though. The only way we have gotten this to work is to remove the two way data binding on the igHierarchical grid and remove retrieving the data source from ngOnInit and put it in the constructor. 

**WORKS**
<ig-hierarchical-grid [(widgetId)]='id2'
                          [options]="hgridOptions" class="table-responsive">
    </ig-hierarchical-grid>
****

**Comment by IG-Stanimir-Dimitrov** [comment]
@LiquidSean - thank you for the workaround. Much appreciated.
