### ISSUE TITLE
igUpload with Spring MVC server

### ISSUE THREAD

**Issue by JiaLiPassion** [IgniteUI/igniteui-angular2#176]
I want to use igUpload with Spring MVC, is there a sample to describe how to implement a spring mvc controller to handle igupload request? 

1. after I define `uploadUrl` in igUpload, in Spring MVC, I can get the file request with the following code.

```javascript
    @RequestMapping(value = "/uploadMyFile", method = RequestMethod.POST)
    @ResponseBody
    public String handleFileUpload(MultipartHttpServletRequest request)
            throws Exception {
        Iterator<String> itrator = request.getFileNames();
        MultipartFile multiFile = request.getFile(itrator.next());
       // save file
      return ''?
    }
``` 

- Is this the best practice? 
- what I should response to client when upload finish?

2. how do I implement a prgressUrl handler in SpringMVC? Now only ASP.NET MVC version available and I don't know where to find the source or API document of it.

Thank you!

**Comment by m-hristov** [comment]
We have implemented PHP server-side wrapper with client-side igUpload - [please check this link](https://www.infragistics.com/community/blogs/damyan_petev/archive/2013/01/30/php-server-side-wrapper-for-the-ignite-ui-file-upload.aspx). In this post you can find a working sample for PHP. Here we have describe how to handle progressURL and how to implement PHP version of upload module. Probably the most important here is how client-side control is "communicating" with server-side and in my opinion this article is very helpful for people implementing server-side wrappers(NOT only on ASP.NET MVC).
About help samples for ASP.NET MVC version you can check this [help topic](https://www.igniteui.com/help/igupload-using-http-handler-and-modules)

Thanks,
Miro Hristov

**Comment by JiaLiPassion** [comment]
@m-hristov , thank you very much, I will read it.
