### ISSUE TITLE
ignite angular 4 grid data binding fails - Data from Web API in json format

### ISSUE THREAD

**Issue by valcs007** [IgniteUI/igniteui-angular2#182]
### Description  
Cannot read property 'length' of undefined 
at IgGridComponent.IgGridBase.ngDoCheck (vendor.bundle.js:42989)
    at checkAndUpdateDirectiveInline (vendor.bundle.js:11368)
    at checkAndUpdateNodeInline (vendor.bundle.js:12853)
    at checkAndUpdateNode (vendor.bundle.js:12792)
    at debugCheckAndUpdateNode (vendor.bundle.js:13651)
    at debugCheckDirectivesFn (vendor.bundle.js:13592)
    at Object.eval [as updateDirectives] (ng:///AppModule/CustomModalComponent.ngfactory.js:312)
    at Object.debugUpdateDirectives [as updateDirectives] (vendor.bundle.js:13577)
    at checkAndUpdateView (vendor.bundle.js:12759)
    at callViewAction (vendor.bundle.js:13122)_

### Steps to reproduce  

1. Get data from Web API as JSON and bind to a local variable productlist
2. Set productlist as datasource  while configuring gridoptions in ts file
3. run angualr 4 app and it fails with the above error.

### Attachments  
Attach a sample if available, and screenshots, if applicable.  

**Component.ts snippet**

ngOnInit() {
     this.id = 'ResultsIgGrid';
     this.productListService.getProducts('A') --- **Web API running in localhost to return json data**
                           .subscribe(prd => this.productList = prd);
                             

      this.gridOptions = {  
      datasource:  this.productList, 
      width: '100%',
			primaryKey: 'SKU',
      renderCheckboxe:true,   
			columns: [
        { 'headerText': 'Select', 'key': 'Select', 'dataType': 'bool', 'width': '15%'},
				// { 'headerText': 'ID', 'key': 'LINK_TO_PRODUCT', 'dataType': 'number', 'width': '10%' },
        { 'headerText': 'Name', 'key': 'SKUE', 'dataType': 'string', 'width': '38%' },
				{ 'headerText': 'Vertical', 'key': 'VERTICAL', 'dataType': 'string', 'width': '10%' },
				{ 'headerText': 'Brand', 'key': 'BRAND', 'dataType': 'string', 'width': '10%' },
				{ 'headerText': 'Family', 'key': 'FAMILY', 'dataType': 'string', 'width': '18%' },
			],
			features: [{
				name: 'Filtering'
			}, {
				name: 'Sorting'
			},
			{
				name: 'Selection',
				mode: 'row',
        multipleSelection:true,
				rowSelectionChanged: function (ui, args) {
					//detailsService.setCurrentCMF(Number(args.row.id));
				}
			}]
		}; 

**Service.ts snippet**

 getProducts(family)
  {
    return  this.http.get('http://localhost:21119/api/products?family='+ family)
                     .map(res => 
                     { 
                       return res.json();
                     });

![image](https://user-images.githubusercontent.com/6827384/28642114-257719d4-7206-11e7-9c5a-53596fc294b3.png)

**Comment by MayaKirova** [comment]
Please note that the option names are case sensitive and that the option for setting the data source is `dataSource`, not datasource. 
Also please make sure that the productList collection is not null/undefined initially when the grid binds to it. You can set it to an empty collection initially, for example:
constructor(){
    this.productList = [];
    this.gridOptions = {  
       dataSource:  this.productList,
…
Let me know if that solves your issue.
