### ISSUE TITLE
igHierarchicalGrid not bind from odata remote url

### ISSUE THREAD

**Issue by dnbhatt1991** [IgniteUI/igniteui-angular2#184]
### Description  
igHierarchicalGrid not bind from odata remote url http://services.odata.org/V4/Northwind/Northwind.svc/Regions 
and also i want to load child data from url http://services.odata.org/V4/Northwind/Northwind.svc/Regions?$expand=Territories

i have try below code from gniteUI/igniteui-angular2 project
### Steps to reproduce  
export class AppComponent {
	private hgridOptions: IgHierarchicalGrid;
	private id: string;
	private data: any;
	private newProduct:any;

	constructor() {
		this.data = NorthwindEmployees.getData();
	//	console.log(this.data);
		this.id ='hgrid1';

		this.hgridOptions = {
			defaultChildrenDataProperty:"Territories",
			autoCommit:true,
			responseDataKey:"value",
			initialDataBindDepth:1,
			dataSource: [],
			dataSourceUrl :"http://services.odata.org/V4/Northwind/Northwind.svc/Regions",
			odata:true,
			width: "100%",
			height: "400px",
			autoGenerateColumns: false,
			autoGenerateColumnLayouts: false,
			columns: [
				{ key: "RegionID", headerText: "RegionI", width:"25%", dataType:"number" }		
			],
			columnLayouts: [
				{
					key: "Territories",
					// responseDataKey: "value",
					primaryKey: "TerritoryID",
					autoGenerateColumns: false,
					width: "100%",
					columns: [
						{ key: "TerritoryID", headerText: "TerritoryID", width:"25%", dataType:"number" }
						
					],
					features: [
						{
							name: "Paging",
							pageSize: "10"
						}
					]
				}
			]
		};
	}
}

**Comment by MayaKirova** [comment]
When there is local and remote data, as in this case:
dataSource: [],
dataSourceUrl :http://services.odata.org/V4/Northwind/Northwind.svc/Regions

,the grid will bind to the local data, but will use the remote url for subsequent remote data operations ( data binding, remote paging, remote sorting etc.).
To force the grid to bind to the remote data you can call the dataBind method, for example:

<ig-hierarchical-grid #grid1
		[(widgetId)]='id'
		[options]="hgridOptions">
</ig-hierarchical-grid>

@ViewChild("grid1") HGrid: IgHierarchicalGridComponent;

ngAfterViewInit() {
    this.HGrid.dataBind();
}

Let me know if that solves your issue.
