### ISSUE TITLE
Update  Angular2 quickstart resources

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-angular2#188]
### Description  

https://github.com/IgniteUI/igniteui-angular2-quickstart
Currently the above quickstart does not run out-of-the-box after using npm install and npm start and errors are thrown. 

### Steps to reproduce  

1. Clone the Repo https://github.com/IgniteUI/igniteui-angular2-quickstart
2. npm install
3. npm start

### Result  
1.The quickstart does not compile and is not served to the browser.
2.Several errors are chained, starting with "error TS2345: Argument of type 'string' is not assig                                                                                                                                                                                               nable to parameter of type 'Expected<Promise<any>>"

### Expected result  
The quickstart compiles and is served to the browser.

### Plausible fix:
updates in package.json:
1. "types/core-js": "^0.9.**34**" TO "types/core-js": "^0.9.**42**", or another compatible version.
2. "typescript": "^2.0.3" TO "typescript": "**2.3.4**"

updates in tsconfig.json:
1. "target": "es5"  TO  "target": "**es2015**"

**Comment by dkamburov** [comment]
Just made a pull request on [https://github.com/IgniteUI/igniteui-angular2-quickstart/pull/5](https://github.com/IgniteUI/igniteui-angular2-quickstart/pull/5)

**Comment by MayaKirova** [comment]
It currently fails with other errors:
 Parameter 'ui' implicitly has an 'any' type.

Adding another pull request to fix that.
https://github.com/IgniteUI/igniteui-angular2-quickstart/pull/6

**Comment by MayaKirova** [comment]
Resolved.
