### ISSUE TITLE
iggrid in igcombo select value with formatter not working

### ISSUE THREAD

**Issue by dnbhatt1991** [IgniteUI/igniteui-angular2#190]
### Description  
i want to select dropdown value in IgGrid. but dropdown source found as undefined

i want to make functionality which has  link mention as below
https://www.igniteui.com/combo/grid-with-combo-editor
my  project is in angular +typescript 
PLease find attach file

### Steps to reproduce  
1. Open Project
2. npm install
3.  npm start

### Result  
You can see grid with combo But dropdown value not selected

### Expected result  
in typescript array is not found in function formatCategoryCombo
 expected result is found droppdown source and also display selected text value in grid.

### Attachments  
i have attach file.
[Iggridcombo.zip](https://github.com/IgniteUI/igniteui-angular2/files/1255369/Iggridcombo.zip)

**Comment by dkamburov** [comment]
I haven't had the change to review your sample yet, but we've had a similar issue before. Can you take a look at it? It might be helpful. [https://github.com/IgniteUI/igniteui-angular2/issues/85]( https://github.com/IgniteUI/igniteui-angular2/issues/85)

**Comment by dnbhatt1991** [comment]
Hello, 
Greetings of the day!

The jQuery.proxy() method is used to preserve a reference to the calling object when the value of the this special operator is changed.
After using the jQuery.proxy() method in mu code  as $.proxy(this.formatCategoryCombo, this)  My problem solved..

Thanks you very much...

**Comment by dkamburov** [comment]
Nice to hear that, can we close the issue in that case :)

**Comment by dnbhatt1991** [comment]
closing the issue
