### ISSUE TITLE
IgHierarchicalGridComponent retains values from previous binding when data source lengths are same

### ISSUE THREAD

**Issue by ruslanss** [IgniteUI/igniteui-angular2#193]
### Description  
We have noticed this issue under certain circumstances - when we switch between data sources with only 1 parent data row, [sometimes] the grid retains this row - when new data source also has 1 row, or retains this row and adds more rows to the grid if the new data sources has more rows.

### Steps to reproduce  

1. bind hierarchical grid to 0 rows
2. change data source to have 1 row
3. change data source to have a different 1 row
4. change back etc.

### Result  
retains data from previous data source

### Expected result  
should always remove data from previous data source

### Attachments  
screenshots showing 1 row retained from the first data source
![1](https://user-images.githubusercontent.com/1591905/30204645-d3caf686-948e-11e7-9411-363d59f9425c.PNG)
![2](https://user-images.githubusercontent.com/1591905/30204649-d63cd9de-948e-11e7-8493-fe82579f9c55.PNG)
![3](https://user-images.githubusercontent.com/1591905/30204652-d862621a-948e-11e7-9cc6-940fc4e1d6fd.PNG)

**Comment by ruslanss** [comment]
the issue lies in the highlighted line of code - if you replace it `with if (true)`, it fixes the issue but may probably cause other issues.
if you have a plunkr template, i should be able to replicate this issue, please provide a link if you have. 
Thanks.
![ignite](https://user-images.githubusercontent.com/1591905/30204775-4f59fde2-948f-11e7-9265-617d335943bf.PNG)

**Comment by MayaKirova** [comment]
I’ve tried reproducing this in an isolated sample, however so far I haven’t had any success in replicating this behavior. I’ve attached the sample I used to test this for your reference : [igHierarchicalGrid.zip](https://github.com/IgniteUI/igniteui-angular2/files/1539113/igHierarchicalGrid.zip). 

Please run it on your side and let me know if you’re able to reproduce the issue with it. 
If not then please feel free to modify it and send it back so that we can investigate it further.

**Comment by ruslanss** [comment]
Hi @MayaKirova ,
all tests fail for me in your sample:


Chrome 63.0.3239 (Windows 10 0.0.0) AppComponent should render title in a h1 tag FAILED
        Can't bind to 'widgetId' since it isn't a known property of 'ig-hierarchical-grid'.
        1. If 'ig-hierarchical-grid' is an Angular component and it has 'widgetId' input, then verify that it is part of this module.
        2. If 'ig-hierarchical-grid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        </select>
        <ig-hierarchical-grid
                                        [ERROR ->][(widgetId)]='id'
                                        [(options)]="hgridOptions" [(dataSource)]="data">
                        </ig-hierarchical-grid>"): ng:///DynamicTestModule/AppComponent.html@7:4
        Can't bind to 'options' since it isn't a known property of 'ig-hierarchical-grid'.
        1. If 'ig-hierarchical-grid' is an Angular component and it has 'options' input, then verify that it is part of this module.
        2. If 'ig-hierarchical-grid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        <ig-hierarchical-grid
                                        [(widgetId)]='id'
                                        [ERROR ->][(options)]="hgridOptions" [(dataSource)]="data">
                        </ig-hierarchical-grid>"): ng:///DynamicTestModule/AppComponent.html@8:4
        Can't bind to 'dataSource' since it isn't a known property of 'ig-hierarchical-grid'.
        1. If 'ig-hierarchical-grid' is an Angular component and it has 'dataSource' input, then verify that it is part of this module.
        2. If 'ig-hierarchical-grid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        <ig-hierarchical-grid
                                        [(widgetId)]='id'
                                        [(options)]="hgridOptions" [ERROR ->][(dataSource)]="data">
                        </ig-hierarchical-grid>"): ng:///DynamicTestModule/AppComponent.html@8:31
        'ig-hierarchical-grid' is not a known element:
        1. If 'ig-hierarchical-grid' is an Angular component, then verify that it is part of this module.
        2. If 'ig-hierarchical-grid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
          <option value="3">3</option>
        </select>
        [ERROR ->]<ig-hierarchical-grid
                                        [(widgetId)]='id'
                                        [(options)]="hgridOptions" [(dataSource)]="data">
        "): ng:///DynamicTestModule/AppComponent.html@6:0
        Error: Template parse errors:
            at syntaxError C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:485:22)
            at TemplateParser.webpackJsonp.../../../compiler/esm5/compiler.js.TemplateParser.parse C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:24633:1)
            at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._parseTemplate C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:34442:1)
            at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileTemplate C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:34417:1)
            at http://localhost:9876/_karma_webpack_/webpack:/C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:34318:48
            at Set.forEach (<anonymous>)
            at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileComponents C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:34318:1)
            at http://localhost:9876/_karma_webpack_/webpack:/C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:34206:1
            at Object.then C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:474:33)
            at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:34204:1)
        Can't bind to 'widgetId' since it isn't a known property of 'ig-hierarchical-grid'.
        1. If 'ig-hierarchical-grid' is an Angular component and it has 'widgetId' input, then verify that it is part of this module.
        2. If 'ig-hierarchical-grid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        </select>
        <ig-hierarchical-grid
                                        [ERROR ->][(widgetId)]='id'
                                        [(options)]="hgridOptions" [(dataSource)]="data">
                        </ig-hierarchical-grid>"): ng:///DynamicTestModule/AppComponent.html@7:4
        Can't bind to 'options' since it isn't a known property of 'ig-hierarchical-grid'.
        1. If 'ig-hierarchical-grid' is an Angular component and it has 'options' input, then verify that it is part of this module.
        2. If 'ig-hierarchical-grid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        <ig-hierarchical-grid
                                        [(widgetId)]='id'
                                        [ERROR ->][(options)]="hgridOptions" [(dataSource)]="data">
                        </ig-hierarchical-grid>"): ng:///DynamicTestModule/AppComponent.html@8:4
        Can't bind to 'dataSource' since it isn't a known property of 'ig-hierarchical-grid'.
        1. If 'ig-hierarchical-grid' is an Angular component and it has 'dataSource' input, then verify that it is part of this module.
        2. If 'ig-hierarchical-grid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
        3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        <ig-hierarchical-grid
                                        [(widgetId)]='id'
                                        [(options)]="hgridOptions" [ERROR ->][(dataSource)]="data">
                        </ig-hierarchical-grid>"): ng:///DynamicTestModule/AppComponent.html@8:31
        'ig-hierarchical-grid' is not a known element:
        1. If 'ig-hierarchical-grid' is an Angular component, then verify that it is part of this module.
        2. If 'ig-hierarchical-grid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
          <option value="3">3</option>
        </select>
        [ERROR ->]<ig-hierarchical-grid
                                        [(widgetId)]='id'
                                        [(options)]="hgridOptions" [(dataSource)]="data">
        "): ng:///DynamicTestModule/AppComponent.html@6:0
        Error: Template parse errors:
            at syntaxError C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:485:22)
            at TemplateParser.webpackJsonp.../../../compiler/esm5/compiler.js.TemplateParser.parse C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:24633:1)
            at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._parseTemplate C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:34442:1)
            at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileTemplate C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:34417:1)
            at http://localhost:9876/_karma_webpack_/webpack:/C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:34318:48
            at Set.forEach (<anonymous>)
            at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileComponents C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:34318:1)
            at http://localhost:9876/_karma_webpack_/webpack:/C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:34206:1
            at Object.then C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/compiler.js:474:33)
            at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents C:/git/igHierarchicalGrid/node_modules/@angular/compiler/esm5/Chrome 63.0.3239 (Windows 10 0.0.0): Executed 3 of 3 (3 FAILED) ERROR (0.095 secs / 0.091 secs)

**Comment by ruslanss** [comment]
OK, so the difference is we are re-using the same object the grid was originally bound to and simply clearing it of all items and re-adding, e.g.:

```
this.data.length = 0;
Array.prototype.push.apply( this.data, this.data1);
```

i believe this works with the normal grid but doesn't with hierarchical.
i have modified your sample to visualise the issue: https://github.com/ruslanss/ignite-ui-grid/commit/3f0821fd04daac543e9b54b5035389e1173e234b

**Comment by ruslanss** [comment]
this is how we fixed it: https://github.com/ruslanss/igniteui-angular2/commit/58affa246d0c2cfb3eabe31bb720a1b35c6e0f75

**Comment by MayaKirova** [comment]
This would work only if there’s a primaryKey defined. However having a primaryKey is not a requirement for the two-way data-binding functionality at this time.
Also comparing the primary key values may not be very reliable in cases when the data source is changed with another that happens to have similar primary key values.
I’ll think on a possible solutions and let you know if I come up with anything.

**Comment by MayaKirova** [comment]
Actually after looking into it further it seems that the add/update/delete row uses API methods that depend on the primaryKey at the moment.
Although most API could work with index instead of key ([addRow](https://www.igniteui.com/help/api/2017.1/ig.datasource#methods:addRow), [deleteRow](https://www.igniteui.com/help/api/2017.1/ig.datasource#methods:deleteRow), [updateRow](https://www.igniteui.com/help/api/2017.1/ig.datasource#methods:updateRow)) the current implementation relies on the primary key values. This is something we could improve in the future.

So from that  perspective your solution is fine, however it may impact a bit the performance if a large data source is supplied to the grid. The IterableDiffers implementation seems to be more optimized for detecting changes in an array so it would be better to use it instead of comparing the primary keys:
```
            //check for changes in collection
            this._changes = this._differ.diff(this._config.dataSource);
            if (this._changes) {
                this._dataSource = jQuery.extend(true, [], this._config.dataSource);               
                this._changes.forEachRemovedItem(function (r) { return _this.deleteRow(r.item[pkKey]); });
		this._changes.forEachAddedItem(function (r) { return _this.addRow(r.item, r.currentIndex); });
            }
```
