### ISSUE TITLE
igGrid - Unable to cancel an event defined in markup

### ISSUE THREAD

**Issue by tommye** [IgniteUI/igniteui-angular2#195]
### Description  
Unable to cancel an event if the event is declared in your template.

Template:
```
<ig-grid [(widgetId)]='id' [(options)]="gridOptions" [(dataSource)]="messages" "primaryKey]="'messageId'" >
        
<column [key]="'messageId'" [headerText]="'message Id'" [dataType]="'string'" [hidden]="'true'"></column>
<column [key]="'englishText'" [headerText]="'English Text'" [dataType]="'string'"></column>
<column [key]="'translatedText'" [headerText]="'Translated Text'" [dataType]="'string'"></column>

<features>
<updating  [editMode]="row" [showDoneCancelButtons]="true" 
 (editRowEnding)="editRowEnding($event)" ></updating>
</features>
</ig-grid>
```

Component:
  ```
 public editRowEnding(e, ui) {          
            return false;       
    }
```

### Steps to reproduce  

1. Define a grid with the updating features in the template
2. Assign an event-handler like rowEnding to the feature
3. Return false from the event handler to cancel the event

### Result  
Unable to cancel an event declared in a template.

### Expected result  
According to the api documentation, an event is cancelled by returning false in the event handler.

**Comment by mharrington622** [comment]
Attaching sample that reproduces the issue.
[igGridUpdating_CancelEvent.zip](https://github.com/IgniteUI/igniteui-angular2/files/1391515/igGridUpdating_CancelEvent.zip)

**Comment by MayaKirova** [comment]
We use EventEmitter to emit the custom component events, however those don’t return the result from the emitted event handler so you cannot cancel the event in that way.
The event passed as part of the arguments however is the custom widget event, so you can directly access and cancel it using preventDefault(), for example:
	onEditRowEnding = (args): boolean => {
		args.event.preventDefault();		
	}

Let me know if that solves your issue.

**Comment by SlavUI** [comment]
Closing the issue @tommye  reopen the issue if you have any further questions :)
