### ISSUE TITLE
ignite fileupload unable to upload multiple files in same http request.

### ISSUE THREAD

**Issue by JiaLiPassion** [IgniteUI/igniteui-angular2#199]
### Description  
Describe the issue.

I want to upload multiple files within the same XHR request, and I use the sample from here, https://jp.igniteui.com/file-upload/multiple-upload, when I select multiple files, it will still send 
two xmlhttp request.
### Steps to reproduce  

1. Step 1
open https://jp.igniteui.com/file-upload/multiple-upload
2. Step 2
select two files.
3. Step 3
Upload and check Network tab in Chrome developer tools, 

### Result  
I hope there is an option to allow use the same XHRHttpRequest to upload multiple files.
just like in plain javascript, we can do like this.

```javascript
function uploadFiles(files) {
    var xhr = new XMLHttpRequest();
    var formData = new FormData();
    xhr.onload = successfullyUploaded;
    xhr.open("POST", "http://localhost:3000/upload", true);
    xhr.setRequestHeader('X-Requested-With','XMLHttpRequest');
    for(var file in files) {
        formData.append("uploads", files[file].data);
    }
    xhr.send(formData);
}
```
### Attachments  
here is a screenshot
<img width="1440" alt="2017-09-26 16 54 42" src="https://user-images.githubusercontent.com/1442575/30848914-9244e4d2-a2db-11e7-890f-900c57b5c251.png">

**Comment by kdinev** [comment]
@JiaLiPassion The current behavior is by design, since the single XHR request is limited on the size of data it can send over, thus if two or more large files add up to more than the XHR limit, then all the uploads will fail.

**Comment by JiaLiPassion** [comment]
@kdinev , thank you for your reply, is that possible to add an option to allow to send multiple files in a single XHR request? For example, some requirement need multiple files as the input of a single transaction.

**Comment by kdinev** [comment]
@JiaLiPassion Sure, this can be logged as a feature request. We need to move the issue to the [ignite-ui](https://github.com/IgniteUI/ignite-ui) repo though.

**Comment by JiaLiPassion** [comment]
@kdinev , thank you!

**Comment by kdinev** [comment]
@JiaLiPassion I've transferred the issue over: https://github.com/IgniteUI/ignite-ui/issues/1228

**Comment by JiaLiPassion** [comment]
@kdinev, got it, thank you very much!
