### ISSUE TITLE
igGrid - autoCommit is not set when defined in template

### ISSUE THREAD

**Issue by tommye** [IgniteUI/igniteui-angular2#205]
### Description  
Setting autoCommit in template doesn't work. Setting the value with GridOptions is ok.

### Steps to reproduce  

1. Define a <ig-grid> in template
2. Set autoCommit as input attribute [autoCommit]="'true'"

### Result  
autoCommit is not set.

### Expected result  
Be able to modify grid options in template

**Comment by dkamburov** [comment]
Actually you are setting it as a string not as a literal, probably this the issue you are seeing 

It should be `[autoCommit]="true"`
I tried in a sample and it is working - http://plnkr.co/edit/3QzCPoPOoYHBYs1WgzXL?p=preview

**Comment by SlavUI** [comment]
Closing the issue @tommye  please reopen if you have any further questions :)
