### ISSUE TITLE
IgGrid Column Summaries not working in angular 4

### ISSUE THREAD

**Issue by RKM001** [IgniteUI/igniteui-angular2#210]
### Description  
In igGrid data is binded with odata with json content type that time summaries column doesn't calculate
particular column value.
### Steps to reproduce  

1. initGrid()
2. rowSummariesColumnSetting array define all columns 
{ columnKey: "key", allowSummaries: true, summaryOperands: [{ type: "sum" }] },
3.features[
            <summaries [columnSettings]="rowSummariesColumnSetting" [type]="remote" [calculateRenderMode]="onselect" [compactRenderingMode]="true" [showSummariesButton]="false"></summaries>

] ...

### Result  
What is the actual result after following the steps to reproduce?

### Expected result  
What is the expected result after following the steps to reproduce?

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by MayaKirova** [comment]
I see you’ve set the summaries to be calculated remotely:
<summaries [columnSettings]="rowSummariesColumnSetting" **[type]="remote"** …>

This means that the remote odata service needs to be able to read the remote request parameters specific for the summaries send from the grid and return the summary results.
If the remote service is not configured to do that then the summaries would be empty.
You can find more information on the exact configuration needed for remote summaries to be handled correctly here:
https://www.igniteui.com/help/handling-remote-features-manually#summaries

Let me know if you have any questions.

**Comment by SlavUI** [comment]
@RKM001 Thee issues seems to be resolved. Let is know if you have further questions. You can also reopen the case of necessary 👍
