### ISSUE TITLE
Add warning message to the npm package about renaming the package

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular2#216]
A warning message would inform the developers that the package will be renamed to igniteui-angular-wrappers

**Comment by kdinev** [comment]
@dkamburov Hold back the warning until the actual rename.

**Comment by dkamburov** [comment]
Shouldn't we have the warning before the renaming. I might have misunderstood something here.

**Comment by kdinev** [comment]
I want us to be able to link directly to the new package in the warning.
