### ISSUE TITLE
Show ig grid column sum in footer

### ISSUE THREAD

**Issue by RKM001** [IgniteUI/igniteui-angular2#224]
Show ig grid column sum in footer
provide any example in plunker in angular 4

**Comment by MayaKirova** [comment]
Here’s a plunker with the igGridComponent with the Summaries feature enabled:
https://plnkr.co/edit/KXkXshfiArkhbVmI7k25?p=preview

Note that each column type has different summaries enabled by default. You can control which summaries are enabled per column using the columnSettings option of the Summaries feature:
https://www.igniteui.com/help/api/2017.2/ui.iggridsummaries#options:columnSettings

You can also read more about the Summaries feature in our documentation:
https://www.igniteui.com/help/iggrid-configuring-column-summaries

Let me know if you have any questions.

**Comment by SlavUI** [comment]
Closing the Issue @RKM001  please reopen if you have any further questions

**Comment by RKM001** [comment]
hi,
its an example  with raw data. i want data from server end and bind into grid with summaries details.
