### ISSUE TITLE
Ignite UI - Bootstrap version

### ISSUE THREAD

**Issue by HRSamy** [IgniteUI/igniteui-angular2#229]
Hi, does Ignite UI support Bootstrap 4 ? I see code sample uses Bootstrap 3.1.1
Thanks

**Comment by kdinev** [comment]
@HRSamy Yes, we do have integration with bootstrap 4. It's a separate theme: https://github.com/IgniteUI/ignite-ui/tree/master/src/css/themes/bootstrap4
