### ISSUE TITLE
Cannot read property 'igGrid' of undefined

### ISSUE THREAD

**Issue by sanathpathiraja** [IgniteUI/igniteui-angular2#49]
Getting error.
Uncaught TypeError: Cannot read property 'igGrid' of undefined

**Comment by kdinev** [comment]
Are you experiencing this with any of the demos we have in the repository?

**Comment by sanathpathiraja** [comment]
yes I saw that.Repository is working.but how we need to import.
I use `npm i igniteui-angular2` 
and import {IgGridComponent}
but getting error 
Uncaught TypeError: Cannot read property 'igGrid' of undefined

**Comment by kdinev** [comment]
Get the code from this demo and see if you are still getting the same error:

https://github.com/IgniteUI/igniteui-angular2/tree/master/samples/igGrid

**Comment by sanathpathiraja** [comment]
import {Component,Inject, ElementRef, EventEmitter, HostListener} from '@angular/core';
import {IgGridComponent} from "../../../../src/igniteui.angular2.ts";
directives: [IgGridComponent]
but still getting this error.
`igniteui.angular2.ts?693a:77Uncaught TypeError: Cannot read property 'igGrid' of undefined`

**Comment by kdinev** [comment]
Sounds like you're missing the script references that Ignite UI requires.

```
<script src="http://cdn-na.infragistics.com/igniteui/latest/js/infragistics.core.js"></script> 
<script src="http://cdn-na.infragistics.com/igniteui/latest/js/infragistics.lob.js"></script>
```

**Comment by sanathpathiraja** [comment]
yes i already use that.
`<script src="http://cdn-na.infragistics.com/igniteui/latest/js/infragistics.core.js"></script> 
<script src="http://cdn-na.infragistics.com/igniteui/latest/js/infragistics.lob.js"></script>`

and 
`<script src="http://code.jquery.com/jquery-1.12.3.js"></script>
<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>`

**Comment by kdinev** [comment]
Could you please attach the sample to reproduce the issue with to this thread?

**Comment by sanathpathiraja** [comment]
I used https://github.com/IgniteUI/igniteui-angular2 document and sample version perfectly. but getting this error. 
igniteui.angular2.ts?693a:77Uncaught TypeError: Cannot read property 'igGrid' of undefined

i think there issue on jQuery.
I already used "jquery": "^2.2.3".
thanks.

**Comment by agusdutra** [comment]
I'm getting the same issue.. Have you solved it somehow that you closed it?

**Comment by dkamburov** [comment]
Can you attach a sample to demonstrate this?

**Comment by Abuleilei** [comment]
I am having this issue as well, and I think I find out the cause (at least something odd). I am using WebPack and the default extension is js instead of ts:
in systemjs.config.js' package:
`'igniteui-angular2': { main: 'igniteui.angular2.js', defaultExtension: 'js' }`

But the igniteui,js is empty, I have run tsc against igniteui,ts several times, still no luck. Any idea why?

Thanks!

**Comment by dkamburov** [comment]
Use `'igniteui-angular2': { main: 'index.js', defaultExtension: 'js' }`
igniteui.ts are typing definitions and the interfaces are compiled to empty file - nothing to worry about here.
If this doesn't resolve please attach a sample so we can investigate it.

**Comment by Abuleilei** [comment]
[IgniteUiTest.zip](https://github.com/IgniteUI/igniteui-angular2/files/666817/IgniteUiTest.zip)

Thanks for your reply! I tried index.js, still having the same issue. Here is a sample, please cd to IgniteUiTest\web, then run "npm install" before start it.

**Comment by dkamburov** [comment]
Hey @Abuleilei ,
There are three problems with your app:

First - you are refering jQuery twice in your index.

Second - `IgGridComponent `should be included into the `declarations `not in the `imports`
`declarations: [ PeopleComponent, IgGridComponent],`

Third - The IgGridComponent expects the data source to be defined 
`people: People[];` should be `people: People[] = [];`

**Comment by Abuleilei** [comment]
Thank you very much @dkamburov ! It works!
