### ISSUE TITLE
Can't import npm module.

### ISSUE THREAD

**Issue by techy2493** [IgniteUI/igniteui-angular2#52]
We can't import the latest npm module.

import {IgGridComponent}            from "igniteui-angular2"

Causes "Cannot find module 'igniteui-angular2' "

When trying require('igniteui-angular2') from the npm website's test module page it generates the following: "Error: Cannot find module 'igniteui-angular2' Error Viewer" 

From package.json:
    "igniteui-angular2": "1.0.1"

**Comment by techy2493** [comment]
If I can provide any further information to help get this resolved quickly please let me know. I can be reached at babel(a t)agvance(dot)net ..

**Comment by kdinev** [comment]
@techy2493 we will take a look at this issue ASAP.

**Comment by dkamburov** [comment]
We'll soon update the version of the npm package, since at this point it is using the angular2 beta.
What you can do at this point is to clone the repo and `npm build` it. In dist/npm you can find all the files that should be into the package.

@techy2493 From the error you are facing, I'm can't say for sure what's causing it. Make sure you are referencing the igniteui.angular2 components and all of their dependencies? Also you could attach an isolated sample, so we can investigate it further.

**Comment by christian-echerer** [comment]
I have the same problem. I would like to import the "npm package" but it does not work:


import { Component } from '@angular/core';
import { ROUTER_DIRECTIVES } from '@angular/router';
import { IgGridComponent } from 'igniteui-angular2/igniteui';

@Component({
    template: `
        <p>Hello from ignite sample grid</p>
    `
})
export class IgniteSampleGridComponent {
}

The error message is:
File: "...igniteui-d.ts" is not a module

I cloned also the repo and tried the output files of "npm build" with the same result.

I'm new to the Angular2 environment, so I might do something wrong during import. Is there a simple Angular2-example using a Infragistc grid based on the npm package?

**Comment by dkamburov** [comment]
Sure, here's the [examples](http://igniteui.github.io/igniteui-angular2/) of all components 
You can pick a widget and then explore their code.

As I said the npm package is not updated yet, you need to clone the latest and npm build it.
You can also attach a sample here, so we can review it.

**Comment by christian-echerer** [comment]
I would like to use the infragistic grid component (IgGridComponent) in the angular2 quickstart sample:
[quickstart](https://github.com/angular/quickstart/blob/master/README.md)

I need a step by step guid, which files i have to change of the quickstart example:
- package.json
- systemjs.config.js
- typings.json
- tsconfig.js
- index.html
- ...

The [examples](http://igniteui.github.io/igniteui-angular2/) are very useful, but the project structure is a little bit different to the angular2 quickstart example (src folder, use of bower, ...).

I think an example based on the angular2 quickstart example would be very useful for all users to test "igniteui-angular2" in their own environment.

**Comment by kdinev** [comment]
@christian-echerer I have created a new issue about this.

**Comment by ybarbaria** [comment]
Same problem : 

`import {IgGridComponent} from 'igniteui-angular2/igniteui.angular2';`

"Cannot find module 'igniteui-angular2' "

Any solution ? DevExtremme and Wijmo are more reactive than you guys..

**Comment by kdinev** [comment]
This issue should be resolve now.
