### ISSUE TITLE
Create step-by-step example for Ignite UI following the Angular 2 quickstart

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular2#54]
Create an example showing how to put an `IgComponent` in the Angular 2 [quickstart](https://github.com/angular/quickstart/blob/master/README.md) example.

Separating this issue from #52

**Comment by sanket360** [comment]
@kdinev Any timeline on when this will be available?

**Comment by kdinev** [comment]
Create a fork of the angular quickstart repo into IgniteUI and modify it to include Ignite UI components in the quickstart :)

**Comment by mpavlinov** [comment]
Link to the repo https://github.com/IgniteUI/igniteui-angular2-quickstart

**Comment by kdinev** [comment]
I ran it and I think it's all good. Closing the issue as completed.
