### ISSUE TITLE
TS2654: Exported external package typings file cannot contain tripleslash references.

### ISSUE THREAD

**Issue by jkumawat** [IgniteUI/igniteui-angular2#63]
Hi Team,

Please remove following error, it stops us to build ASP.NET Core and Angular2 Web project in VS2015 Enterprise. 

Error	TS2654 -->

Build:Exported external package typings file cannot contain tripleslash references. Please contact the package author to update the package definition.	

**Error At ...\node_modules\igniteui-angular2\igniteui.angular2.d.ts**

Thank you!

Regards,
Jeetendra Kumawat

**Comment by fmocorreia** [comment]
Any workaround to this problem?

**Comment by dkamburov** [comment]
Didn't close it, because npm package should also be updated.

**Comment by kdinev** [comment]
Ok, I can create a release and then close it?

**Comment by kdinev** [comment]
https://github.com/IgniteUI/igniteui-angular2/releases/tag/1.0.5
