### ISSUE TITLE
IgHierarchicalGridComponent from ignite UI.

### ISSUE THREAD

**Issue by ankurshah32** [IgniteUI/igniteui-angular2#67]
Hi ,

Let me tell you what I am expecting from infragistic table.
There is Type (VAR, ATT, VIS) field in below table. For every type of sub table we need different type of table. 
How can we achieve this?
Please have a look at the main table below and respective sub tables.  

https://cloud.githubusercontent.com/assets/4920253/17297089/7244e95c-5804-11e6-9f4a-7c2e75453b99.png
 

For VAR sub-table looks like this. 

 https://cloud.githubusercontent.com/assets/4920253/17297088/724048c0-5804-11e6-864e-02d8de8016f9.png

For ATT sub-table look like this

 https://cloud.githubusercontent.com/assets/4920253/17297086/723db6d2-5804-11e6-866d-0cad1eea54e0.png

For VIS sub-table look like this

https://cloud.githubusercontent.com/assets/4920253/17297087/723e9778-5804-11e6-8b0d-ccd76892627f.png

 

Thanks
Ankur SHah

**Comment by kdinev** [comment]
@ankurshah32 I don't quite understand your question. Do you have a specific issue with the `igHierarchicalGrid`? You can use different type of entities for each of the layouts of the hierarchical grid, so the provided screenshots are achievable with the hierarchical grid component.
