### ISSUE TITLE
UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.4

### ISSUE THREAD

**Issue by sanket360** [IgniteUI/igniteui-angular2#73]
I am referring igniteui-angular2 package from this link - https://www.npmjs.com/package/igniteui-angular2

I tried to run this command - `npm i igniteui-angular2`

But this gave me below error-
![a2-igniteui-rc3](https://cloud.githubusercontent.com/assets/16756121/17771967/c9ca5e70-6563-11e6-8fba-d44f5a4a0d07.PNG)

How to use this package with Angular2 RC4?

**Comment by kdinev** [comment]
#72

**Comment by sanketkubal** [comment]
@kdinev As a part of your Sprint 11, npm package will be upgraded to Angular2 RC4 or RC5?

**Comment by kdinev** [comment]
@sanketkubal Upgrade to RC5 is planned.

**Comment by sanket360** [comment]
@kdinev Thanks :+1:

**Comment by sanket360** [comment]
I tried newer version of igniteui-angular2 **1.0.6** but still receiving the error.

![1 0 6](https://cloud.githubusercontent.com/assets/16756121/18032424/f6a1dc82-6d21-11e6-88f2-15ce954c8c6f.PNG)

**Comment by kdinev** [comment]
@sanket360 The package.json is now updated. Can you try version 1.0.7?

**Comment by sanket360** [comment]
version 1.0.7 working fine.

![capture](https://cloud.githubusercontent.com/assets/16756121/18049853/6d988458-6e08-11e6-80fe-a69a087bb789.PNG)

**Comment by kdinev** [comment]
@sanket360 Thank you for your patience! I'm closing the issue.
