### ISSUE TITLE
error TS2304: Cannot find name 'IgPivotGrid'.

### ISSUE THREAD

**Issue by sanket360** [IgniteUI/igniteui-angular2#79]
Hi

I am trying to use IgPivotGrid and IgPivotDataSelector with Angular2 RC5 application.
For this, I have installed igniteui-angular2 version 1.0.7

In my component, I am trying to use these IgPivotGrid and IgPivotDataSelector. However, I am getting error. Please see below screenshot for more details and let me know if I am missing anything here.

![capture](https://cloud.githubusercontent.com/assets/16756121/18075710/d86c44ae-6e94-11e6-9bcf-c0bed0fa1d4a.PNG)

**Comment by sanket360** [comment]
Any update on this?

**Comment by dkamburov** [comment]
Add ref path to at the top of your app.component.ts file

/// <reference path="../node_modules/igniteui-angular2/igniteui.d.ts" />

**Comment by sanket360** [comment]
This doesn't work for me.  

After adding ref path, I am getting these errors-

> node_modules/igniteui-angular2/igniteui.d.ts(7796,2): error TS2382: Specialized
> overload signature is not assignable to any non-specialized signature.

![31aug error](https://cloud.githubusercontent.com/assets/16756121/18138883/822a45b2-6fcc-11e6-8ace-3f2e0c886bf3.PNG)

**Comment by sanket360** [comment]
Could you please help me on this?

**Comment by sanket360** [comment]
Its pending from last 5 days. Could you please help me on this?

**Comment by dkamburov** [comment]
Instead of tripleslash refs you could specify files in tsconfig.json

Example of tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "files": [
    "node_modules/igniteui-angular2/jquery.d.ts",
    "node_modules/igniteui-angular2/igniteui.d.ts"
  ]
}
```
You may also need to restart VS code.

**Comment by sanket360** [comment]
@dkamburov thanks for your response. Now I am able to compile my application. However, when I run my application using npm start command, I get below runtime errors in browser console-

> 
> zone.js:484 Unhandled Promise rejection: Template parse errors:
> Can't bind to 'widgetId' since it isn't a known property of 'ig-pivot-grid'.
> 1. If 'ig-pivot-grid' is an Angular component and it has 'widgetId' input, then verify that it is part of this module.
> 2. If 'ig-pivot-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
>  ("
> <div class="row">
> 	<div class="col-md-12">
> 		<ig-pivot-grid [ERROR ->][widgetId]="gridId" [options]="optsGrid">
> 		</ig-pivot-grid>
> 		
> "): AppComponent@4:17
> Can't bind to 'options' since it isn't a known property of 'ig-pivot-grid'.
> 1. If 'ig-pivot-grid' is an Angular component and it has 'options' input, then verify that it is part of this module.
> 2. If 'ig-pivot-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
>  ("
> <div class="row">
> 	<div class="col-md-12">
> 		<ig-pivot-grid [widgetId]="gridId" [ERROR ->][options]="optsGrid">
> 		</ig-pivot-grid>
> 		
> "): AppComponent@4:37
> .........................

This is how my pivotgrid template looks like-
```
<div class="row">
	<div class="col-md-12">
		<ig-pivot-grid [widgetId]="gridId" [options]="optsGrid">
		</ig-pivot-grid>
		
		<ig-pivot-data-selector [widgetId]="selectorId" [options]="optsSelector">
		</ig-pivot-data-selector>
		
	</div>
</div>
```


This is how my app.module.ts looks like-

```
import { NgModule, CUSTOM_ELEMENTS_SCHEMA }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppComponent }  from './app.component';

import {IgPivotDataSelectorComponent, IgPivotGridComponent} from "igniteui-angular2";

@NgModule({
  imports:      [ BrowserModule ],
  declarations: [ AppComponent, IgPivotDataSelectorComponent, IgPivotGridComponent],
  bootstrap:    [ AppComponent ],
  schemas:      [ CUSTOM_ELEMENTS_SCHEMA ]
})
export class AppModule { }

```

Anything I am missing here?

**Comment by dkamburov** [comment]
Have updated igniteui-angular2 npm package?

I managed to create an app with your app.module.ts and app.component.ts without reproducing the error you're describing.

Attaching it here.
[Angular2_igPivotGrid.zip](https://github.com/IgniteUI/igniteui-angular2/files/461579/Angular2_igPivotGrid.zip)

**Comment by sanket360** [comment]
I am using igniteui-angular2 npm package version **1.0.7**

Coupld of points I notice in your sample-
1. I don't see this igniteui-angular2 in your package.json.
2. None of your angular2 components files in app folder, using IgPivotGridComponent.

**Comment by dkamburov** [comment]
My apologize, I've attached a wrong sample. Attaching the correct one here.
[Angular2_igPivotGrid.zip](https://github.com/IgniteUI/igniteui-angular2/files/461863/Angular2_igPivotGrid.zip)

**Comment by sanket360** [comment]
@dkamburov Sorry to bother you again but I am still facing issue.

Difference I could see in my sample and your sample is- I am referring all packages from node_modules whereas you are referring from https://unpkg.com I am not sure if this is a problem. Could you please take a look at my sample and let me know if I am missing anything. 

All you need to do is run these 2 commands - npm install and npm start.
[angular2-RC5-igniteUI-28Aug.zip](https://github.com/IgniteUI/igniteui-angular2/files/463173/angular2-RC5-igniteUI-28Aug.zip)

**Comment by dkamburov** [comment]
@sanket360 you need to include references to the IgniteUI widgets into your index.html

CDN to combined css files:
```
<!-- Ignite UI Required Combined CSS Files -->
<link href="http://cdn-na.infragistics.com/igniteui/2016.1/latest/css/themes/infragistics/infragistics.theme.css" rel="stylesheet" />
<link href="http://cdn-na.infragistics.com/igniteui/2016.1/latest/css/structure/infragistics.css" rel="stylesheet" 
```
CDN to combined js files:
```
<!-- Ignite UI Required Combined JavaScript Files -->
<script src="http://cdn-na.infragistics.com/igniteui/2016.1/latest/js/infragistics.core.js"></script>
<script src="http://cdn-na.infragistics.com/igniteui/2016.1/latest/js/infragistics.lob.js"></script>
```

**Comment by sanket360** [comment]
I can see these errors in my browser console-
```
Font from origin 'http://cdn-na.infragistics.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 403.

cdn-na.infragistics.com/igniteui/2016.1/latest/css/structure/fonts/jquery-ui.woff:1 GET http://cdn-na.infragistics.com/igniteui/2016.1/latest/css/structure/fonts/jquery-ui.woff 
(index):1 

Font from origin 'http://cdn-na.infragistics.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 403.

cdn-na.infragistics.com/igniteui/2016.1/latest/css/structure/fonts/jquery-ui.ttf:1 GET http://cdn-na.infragistics.com/igniteui/2016.1/latest/css/structure/fonts/jquery-ui.ttf 
```

How to avoid these errors?

Also, does ignite ui provide multiple themes (light and dark themes)?

**Comment by dkamburov** [comment]
To remove the error for Cross-Origin Resource sharing you can download the product from [here](https://www.igniteui.com/download) and include it into your app.

Sure, Infragistics offers the following themes you can include in your website:

- Infragistics Theme
- Infragistics 2012 Theme
- Metro Theme
- iOS Theme

Bootstrap Themes:
- Default
- Superhero
- Yeti
- Flatly

You can also see some of them [here](http://www.igniteui.com/themes/overview)

Also go ahead and review the following [topic](http://www.igniteui.com/help/deployment-guide-styling-and-theming) about the IgniteUI themes and their customization.

**Comment by sanket360** [comment]
@dkamburov Thanks for your help. :+1:
