### ISSUE TITLE
Columns under multi-column header do not display data.

### ISSUE THREAD

**Issue by igMPeterson** [IgniteUI/igniteui-angular2#80]
When using the igGrid with Angular 2 and the grid has multi-column headers any column that is under a multi-column header will not display data.
[Angular2_Service.zip](https://github.com/IgniteUI/igniteui-angular2/files/449854/Angular2_Service.zip)

**Comment by dkamburov** [comment]
This is a bug related to [renderNewRow](http://www.igniteui.com/help/api/2016.1/ui.iggrid#methods:renderNewRow) API in the igGrid(it wasn't able to recognize if there are multi column headers) and it is working fine with the latest dev code.

**Comment by kdinev** [comment]
@igMPeterson @dkamburov I will mark this as fixed as soon as 16.2 is released.

**Comment by boogher** [comment]
I am having the same issue, but I am using code in the Angular2_API branch. Does the Angular2_API branch have this fix.
