### ISSUE TITLE
Update to Angular 2.0.0

### ISSUE THREAD

**Issue by AndiThoma** [IgniteUI/igniteui-angular2#83]
Please update to angluar 2.0.0

**Comment by christian-echerer** [comment]
We had an update on rc6 today unfortunately roll back because igniteui-angular2 still using outdated angular2 classes, which were removed in rc6.

**Comment by kdinev** [comment]
@AndiThoma I was just about to update this issue, but you've already done it ~40 minutes before me :)

**Comment by kdinev** [comment]
Updating the issue again!

**Comment by AndiThoma** [comment]
final, unbelievable !!! :D
