### ISSUE TITLE
grid with editable combobox angular 2

### ISSUE THREAD

**Issue by kkarandikar0807** [IgniteUI/igniteui-angular2#85]
Hi i could find the jquery code, but have you guys updated an  table with editable dropdown in typecript?

**Comment by dkamburov** [comment]
I've prepared a sample with igCombo inside of an igGrid and I'm attaching it here:

To run it use `npm install` and then `npm start`

[igCombo_igGrid_Angular2.zip](https://github.com/IgniteUI/igniteui-angular2/files/493524/igCombo_igGrid_Angular2.zip)

**Comment by kdinev** [comment]
Closing this one because it's inactive.
